(load "C:\\AZT\\azt_standard.lsp")
(load "C:\\AZT\\azt_dane.lsp")
(load "C:\\AZT\\azt_szablony.lsp")
(load "C:\\AZT\\azt_zelbet.lsp")
(load "C:\\AZT\\azt_stal.lsp")
(load "C:\\AZT\\azt_stal_baza.lsp")
(load "C:\\AZT\\azt_makra.lsp")
(princ "\n###############################################################")
(princ "\n##################### AZ TOOLBAR WLACZONY #####################")
(princ "\n###############################################################")
(princ)